#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d           misc

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#7389aa"
bspc config focused_border_color "#3bb6e2"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a code desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=offs

feh --bg-scale ~/cyberpunk.jpg &
polybar &
picom &
